version: '3.1'
services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql